#!/bin/sh
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @author    OpenMediaVault Plugin Developers <plugins@omv-extras.org>
# @copyright Copyright (c) 2009-2013 Volker Theile
# @copyright Copyright (c) 2013-2017 OpenMediaVault Plugin Developers
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

SYSTEMD_DIR="/etc/systemd/system"
XPATH="/config/services/aoe"

# Create target services
index=$(omv_config_get_count "${XPATH}/targets/target")
while [ ${index} -gt 0 ]; do

    # Get the shared folder reference and path
    shelf=$(omv_config_get "${XPATH}/targets/target[position()=${index}]/shelf")
    slot=$(omv_config_get "${XPATH}/targets/target[position()=${index}]/slot")
    netif=$(omv_config_get "${XPATH}/targets/target[position()=${index}]/netif")
    filename=$(omv_config_get "${XPATH}/targets/target[position()=${index}]/filename")

    cat > ${SYSTEMD_DIR}/aoe-${shelf}-${slot}.service << EOF
[Unit]
Description=ata over ethernet target for ${shelf} ${slot}
After=network.target

[Service]
Type=oneshot
ExecStart=/usr/sbin/vbladed ${shelf} ${slot} ${netif} ${filename}
RemainAfterExit=true

[Install]
WantedBy=multi-user.target
EOF

    index=$(( ${index} - 1 ))
done

exit 0
