#!/bin/bash

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

remove_action() {
    # remove aoe module file
    if [ -f /etc/modules-load.d/aoe.conf ]; then
        rm /etc/modules-load.d/aoe.conf
    fi

    # remove unit files
    find /etc/systemd/system/ -maxdepth 1 -name "aoe*.service" -delete
    systemctl daemon-reload

    # Activate trigger to purge cached files.
    dpkg-trigger update-fixperms
}

case "$1" in
	purge)
		remove_action
		echo "Cleaning up configuration database ..."
		omv_config_delete "/config/services/aoe"
	;;

	remove)
		remove_action
	;;

	upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
	;;

	*)
		echo "postrm called with unknown argument '$1'" >&2
		exit 1
	;;
esac

exit 0
