#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    configure)
        # add aoe module and load it
        cat "aoe aoe_deadsecs=10" > /etc/modules-load.d/aoe.conf
        modprobe aoe aoe_deadsecs=10

        # discover any AoE storage devices
        aoe-discover

        # Activate package triggers. These triggers are only set during the
        # package installation.
        dpkg-trigger update-fixperms
        dpkg-trigger update-locale

        echo "Updating configuration database ..."
        omv-confdbadm create "conf.service.aoe"
        if [ -n "$2" ]; then
            omv-confdbadm migrate "conf.service.aoe" "${2}"
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument" >&2
        exit 1
    ;;
esac

exit 0
