#!/bin/sh
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @author    OpenMediaVault Plugin Developers <plugins@omv-extras.org>
# @copyright Copyright (c) 2009-2018 Volker Theile
# @copyright Copyright (c) 2013-2018 OpenMediaVault Plugin Developers
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

SYSTEMD_DIR="/etc/systemd/system"
XPATH="/config/services/aoe"

# Create target services
index=$(omv_config_get_count "${XPATH}/targets/target")
while [ ${index} -gt 0 ]; do
    shelf=$(omv_config_get "${XPATH}/targets/target[position()=${index}]/shelf")
    slot=$(omv_config_get "${XPATH}/targets/target[position()=${index}]/slot")
    netif=$(omv_config_get "${XPATH}/targets/target[position()=${index}]/netif")
    filename=$(omv_config_get "${XPATH}/targets/target[position()=${index}]/filename")
    direct=$(omv_config_get "${XPATH}/targets/target[position()=${index}]/direct")
    sync=$(omv_config_get "${XPATH}/targets/target[position()=${index}]/sync")
    service="${SYSTEMD_DIR}/aoe-${shelf}-${slot}.service"

    if [ "${direct}" = "1" ]; then
        d="-d "
    else
        d=""
    fi

    if [ "${sync}" = "1" ]; then
        s="-s "
    else
        s=""
    fi

    cat > ${service} << EOF
[Unit]
Description=ata over ethernet target for ${shelf} ${slot}
After=network.target

[Service]
Type=oneshot
ExecStart=/usr/sbin/vbladed ${d}${s}${shelf} ${slot} ${netif} ${filename}
RemainAfterExit=true

[Install]
WantedBy=local-fs.target
EOF

    index=$(( ${index} - 1 ))
done
